---
title: "Untitled"
author: "Yi Wang"
date: "Oct. 2018"
output: html_document
---
## Homework 4

## Write the R code using ggplot function to recreate the graph from the Lecture 8 notes
```{r}
#The code in the Lecture 8 notes#
curve(dnorm, from=-3, to=3, xlim=c(-3, 6), lwd=2, col=4, axes=FALSE, xlab=NA, ylab=NA)
curve(dnorm(x, mean=3.2), add=TRUE, col=2, lwd=2, from=0, to=6)
coord.x <- c(qnorm(0.95),
seq(qnorm(0.95), 0, by=-0.01), 0)
coord.y <- c(0, dnorm(coord.x[-c(1, length(coord.x))], mean=3.2), 0)
polygon(coord.x, coord.y, col=rgb(1, 0, 0, 0.5))
coord.x <- c(qnorm(0.95),
seq(qnorm(0.95), 3, by=0.01), 3)
coord.y <- c(0, dnorm(coord.x[-c(1, length(coord.x))]), 0)
polygon(coord.x, coord.y, col=rgb(0, 0, 1, 0.5))
abline(v = qnorm(0.95), lty=2, lwd=2)
text(1, 0.02, labels = expression(beta))
text(2, 0.02, labels = expression(alpha), col = "white")
axis(1, at = c(0, 3.2), labels = c(expression(theta_0), expression(theta_a)))
axis(2)
box()
legend("topleft", c("Type I error", "Type II error"), fill=c(rgb(0, 0, 1, 0.5), rgb(1, 0, 0, 0.5)))
```

```{r}
#Use ggplot function to create the graph#
library(tidyverse)
ggplot(NULL, aes(x = c(-3, 6), y = c(0, 0.4))) +
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1), lwd = 1, xlim = c(-3, 3), color = "blue") +
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1), xlim = c(qnorm(0.95), 3), geom = "area", col = "black", alpha = 0.4, aes(fill = "red")) + 
  stat_function(fun = dnorm, args = list(mean = 3.2, sd = 1), lwd = 1, xlim = c(0, 6), color = 'red') +
  stat_function(fun = dnorm, args = list(mean = 3.2, sd = 1), xlim = c(0, qnorm(0.95)), geom = "area", col = "black", alpha = 0.4, aes(fill = "blue")) +
  geom_vline(xintercept = qnorm(0.95), linetype = 2, lwd=1) +
  annotate("text", x = 2, y = 0.02, label = expression(alpha), color = "white", size = 5) +
  annotate("text", x = 1, y = 0.02, label = expression(beta), size = 5) +
  scale_fill_manual(values = c("red", "blue"), label = c("Type I error", "Type II error")) +
  scale_x_continuous(breaks = c(0, 3.2), labels = c(expression(theta[0]), expression(theta[a]))) +
  theme_bw() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        legend.title = element_blank(),
        legend.justification = c(0, 1),
        legend.position = c(0, 1),
        legend.box.margin = margin(c(1, 0, 0, 1)),
        legend.box.background = element_rect(fill = NA),
        legend.text = element_text(size = 12, margin = margin(l = 10)),
        axis.title = element_blank(),
        axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 12, angle = 90, hjust = 0.5, face = "bold", vjust = 3),
        axis.ticks.length = unit(3, "mm")) 
  
```


##  Implement a function that will check if a given positive integer is a prime number
```{r}
check <- function(a){
  if(a <= 0) paste("The input number must be positive.")
  else if(a == 1) paste("The input number is 1 and it's not a prime number.")
  else if(a == 2) paste("It's a prime number.")
  else{
    for (i in 2:a) {
      if(a %% i == 0){
        return(paste("It's not a prime number"))
      }
       
      else
        return(paste("It's a prime number."))
    }
  }
}

check(-1)
check(0)
check(1)
check(2)
check(4)
check(5)
check(3)
check(6)
```


